"""Generate docs/TOKENS.md from base/base.css.

The defaults block at the top of base.css is the token list: every --ts-*
token a skin may set, its group and its default. The rules below it say where
each token is used. Re-run after changing base.css:

    python scripts/gen-token-docs.py
"""
import collections, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
base = open(os.path.join(ROOT, 'base', 'base.css'), encoding='utf-8').read()

# Hand-written descriptions for the core roles; everything else is described
# by its default and where it's used.
CORE = {
    'bg': 'Page background.',
    'surface': 'Panels, widgets, dropdowns, modals.',
    'surface-raised': 'Headings, table heads, buttons, the navbar.',
    'surface-hover': 'Hovered and selected rows, links, menu items.',
    'border': 'Borders and dividers.',
    'text': 'Body text.',
    'text-dim': 'Secondary text: navbar links, footers, pagination.',
    'text-mute': 'Least prominent text: placeholders, help text, disabled items.',
    'text-bright': 'Headings and text on coloured backgrounds.',
    'accent': 'The skin\'s signature colour: active tabs, hover edges, modal tops.',
    'link': 'Links.',
    'highlight': 'Focus rings and hover edges on inputs and menus.',
    'success': 'Up, OK.',
    'warning': 'Warning.',
    'danger': 'Down, error.',
    'info': 'Informational, and primary buttons by default.',
    'danger-text': 'Readable red for text on dark surfaces (device-down links).',
    'font-display': 'Headings, navbar, panel titles, buttons.',
    'font-mono': 'Data: table cells, labels, hostnames.',
    'radius-sm': 'Corner radius; the other radii default to it.',
}

start = base.index('html.dark {')
end = base.index('\n}', start)
defaults_block = base[start:end]
rules = base[end:]

groups = collections.OrderedDict()
group = None
for line in defaults_block.split('\n'):
    m = re.match(r'\s*/\* (.+?) \*/', line)
    if m:
        group = m.group(1)
        groups[group] = []
        continue
    m = re.match(r'\s*--ts-([\w-]+):\s*(.+);$', line)
    if m:
        groups[group].append((m.group(1), m.group(2)))

# usage: token -> [(selector, property)]
usage = collections.defaultdict(list)
for m in re.finditer(r'([^{}]+)\{([^{}]*)\}', rules):
    selector = ' '.join(m.group(1).split())
    for decl in m.group(2).split(';'):
        if ':' not in decl:
            continue
        prop, value = decl.split(':', 1)
        for tok in re.findall(r'var\(--ts-([\w-]+)\)', value):
            usage[tok].append((selector, prop.strip()))
referenced_by = collections.defaultdict(list)
for items in groups.values():
    for name, value in items:
        for tok in re.findall(r'var\(--ts-([\w-]+)\)', value):
            referenced_by[tok].append(name)


def short(selector):
    first = selector.split(',')[0].replace('html.dark ', '').strip()
    more = selector.count(',')
    return first + (f' (+{more})' if more else '')


def used(name):
    parts = [f'`{short(s)}` {p}' for s, p in usage.get(name, [])[:3]]
    if len(usage.get(name, [])) > 3:
        parts.append(f'+{len(usage[name]) - 3} more')
    if referenced_by.get(name):
        parts.append('default of ' + ', '.join(f'`{n}`' for n in referenced_by[name][:4]) +
                     (' …' if len(referenced_by[name]) > 4 else ''))
    return '; '.join(parts) or '—'


def cell(v):
    return '`' + v.replace('|', '\\|') + '`'


# Component tokens are grouped in base.css by where their default came from;
# a reader wants them by what they style.
COMPONENTS = [
    ('Page and links', ('root', 'body', 'link', 'hr', 'scrollbar')),
    ('Navbar', ('navbar',)),
    ('Dropdowns', ('dropdown',)),
    ('Panels', ('panel',)),
    ('Dashboard widgets', ('widget',)),
    ('Tables', ('table', 'bootgrid')),
    ('Buttons', ('btn', 'lnms')),
    ('Forms', ('input', 'addon', 'switch', 'typeahead')),
    ('Alerts, labels, badges', ('alert', 'label', 'badge', 'user')),
    ('Tabs and page menus', ('tab', 'tabs', 'pagemenu')),
    ('Everything else', ()),
]
pool = []
for g in [g for g in groups if g.startswith('Components')]:
    pool += groups.pop(g)
for title, prefixes in COMPONENTS:
    items = [it for it in pool if it[0].split('-')[0] in prefixes] if prefixes else list(pool)
    pool = [it for it in pool if it not in items]
    if items:
        groups['Components: ' + title] = sorted(items)

total = sum(len(v) for v in groups.values())
out = [
    '# Token reference',
    '',
    '<!-- Generated by scripts/gen-token-docs.py from base/base.css. Do not edit by hand. -->',
    '',
    f'A skin is a token file, `skin.css`, that sets `--ts-*` custom properties on `html.dark`. '
    f'There are {total} tokens. Every one has a default in `base/base.css`, so a skin sets only what it '
    'wants to change. Setting the 20 core roles is enough for a complete skin: the rest are derived from '
    'them. See `examples/minimal/skin.css`.',
    '',
    'A skin may also define its own palette as `--p-*` properties and refer to them from its token values. '
    'Nothing else is allowed in a token file (docs/PLUGIN.md, "The token file").',
    '',
]
for g, items in groups.items():
    # "Core roles. A skin normally sets..." -> heading, then the sentence
    head, _, rest = g.partition(': ')
    if head == 'Components':
        head, rest = rest, ''
    out += [f'## {head}', '']
    if rest:
        out += [rest[0].upper() + rest[1:], '']
    if g.startswith('Core roles'):
        out += ['| Token | Default | Used for |', '|---|---|---|']
        out += [f'| `--ts-{n}` | {cell(v)} | {CORE.get(n, "")} |' for n, v in items]
    else:
        out += ['| Token | Default | Used by |', '|---|---|---|']
        out += [f'| `--ts-{n}` | {cell(v)} | {used(n)} |' for n, v in items]
    out.append('')

path = os.path.join(ROOT, 'docs', 'TOKENS.md')
open(path, 'w', encoding='utf-8', newline='\n').write('\n'.join(out))
print(f'wrote {path}: {total} tokens in {len(groups)} groups')
