<?php

namespace Xblossia\ThemeSelector;

use Throwable;
use Xblossia\ThemeSelector\Skin\CompiledSkin;
use Xblossia\ThemeSelector\Skin\Manifest;

/**
 * Puts a validated skin into the web root, and takes one out.
 *
 * Only CompiledSkin gets here, so everything written was generated by the
 * validator: one skin.css of printable ASCII. What this class adds is the
 * filesystem discipline:
 *
 * - Nothing appears at its final path until it is complete. The stylesheet is
 *   written into a staging directory, read back and hashed, and only then
 *   renamed into place. A crash or a full disk leaves either the old skin or a
 *   staging directory that the next install sweeps up, never half a skin.
 * - Replacing and deleting are renames first and removals second, so the skin
 *   is gone or intact at every instant and a failure can be rolled back.
 * - Installs are serialised with a lock file, so two admins uploading at once
 *   can't interleave.
 * - Removal never follows a symlink: it deletes links, not their targets, and
 *   refuses any path that resolves outside the skins directory.
 * - Ids come from the validated manifest (a strict slug) and are re-checked
 *   here, and a bundled skin's id can never be taken or removed.
 * - The registry row is what makes the directory a skin (see SkinRepository);
 *   if saving it fails the directory is rolled back.
 */
class SkinInstaller
{
    public function __construct(
        private readonly string $publicDir,
        private readonly SkinRepository $skins,
        private readonly SkinRegistry $registry,
        private readonly DefaultSkin $default,
    ) {
    }

    /**
     * @return bool  whether an existing uploaded skin was replaced
     *
     * @throws InstallException
     */
    public function install(CompiledSkin $skin, ?int $userId): bool
    {
        $id = $skin->id();
        if (! SkinRepository::isValidId($id) || in_array($id, Manifest::RESERVED_IDS, true)) {
            throw new InstallException('That skin id is not allowed.');
        }
        if ($this->skins->isBundled($id)) {
            throw new InstallException('The id "' . $id . '" belongs to a bundled skin. Choose a different id in skin.json.');
        }

        $skinsDir = $this->publicDir . '/skins';
        $lock = $this->lock();
        $old = null;
        try {
            $this->ensureDir($skinsDir);
            $this->sweep($skinsDir);

            $stage = $skinsDir . '/.stage-' . bin2hex(random_bytes(8));
            if (! mkdir($stage, 0755)) {
                throw new InstallException('Could not create a working directory; check that the web server user can write ' . $skinsDir . '.');
            }
            try {
                $file = $stage . '/skin.css';
                if (file_put_contents($file, $skin->css, LOCK_EX) !== strlen($skin->css) || ! chmod($file, 0644)) {
                    throw new InstallException('Could not write the stylesheet.');
                }
                // Read it back: what is on disk must be exactly what was validated.
                if (hash_file('sha256', $file) !== hash('sha256', $skin->css)) {
                    throw new InstallException('The stylesheet did not verify after writing.');
                }

                $target = $skinsDir . '/' . $id;
                if (is_link($target) || (file_exists($target) && ! is_dir($target))) {
                    throw new InstallException('Something that is not a skin directory is in the way.');
                }
                if (is_dir($target)) {
                    $old = $skinsDir . '/.old-' . bin2hex(random_bytes(8));
                    if (! rename($target, $old)) {
                        $old = null;
                        throw new InstallException('Could not replace the existing skin.');
                    }
                }
                if (! rename($stage, $target)) {
                    if ($old !== null) {
                        rename($old, $target);
                    }
                    throw new InstallException('Could not put the skin in place.');
                }
            } catch (Throwable $e) {
                $this->removeTree($stage);
                throw $e;
            }

            try {
                $this->registry->save($skin, $userId);
            } catch (Throwable $e) {
                // The directory is only a skin once its row exists: undo it.
                $this->removeTree($skinsDir . '/' . $id);
                if ($old !== null) {
                    rename($old, $skinsDir . '/' . $id);
                }
                throw new InstallException('Could not record the skin in the database; see the LibreNMS log.', 0, $e);
            }
            if ($old !== null) {
                $this->removeTree($old);
            }
        } finally {
            $this->unlock($lock);
        }

        // The palette may have changed under a skin that is the default.
        if ($this->default->current() === $id) {
            $this->default->reapply();
        }

        return $old !== null;
    }

    /**
     * @throws InstallException
     */
    public function remove(string $id): void
    {
        if (! SkinRepository::isValidId($id)) {
            throw new InstallException('That skin id is not valid.');
        }
        if ($this->skins->isBundled($id)) {
            throw new InstallException('Bundled skins can not be removed.');
        }
        if ($this->registry->find($id) === null) {
            throw new InstallException('There is no uploaded skin with that id.');
        }

        $skinsDir = $this->publicDir . '/skins';
        $lock = $this->lock();
        try {
            // Clear the default first: that puts the graph colours back, and
            // must happen while the skin (and its palette) still exists.
            if ($this->default->current() === $id) {
                $this->default->set(null);
            }

            $target = $skinsDir . '/' . $id;
            $gone = null;
            if (is_link($target)) {
                @unlink($target);
            } elseif (is_dir($target)) {
                $gone = $skinsDir . '/.old-' . bin2hex(random_bytes(8));
                if (! rename($target, $gone)) {
                    throw new InstallException('Could not remove the skin files.');
                }
            }
            try {
                $this->registry->delete($id);
            } catch (Throwable $e) {
                if ($gone !== null) {
                    rename($gone, $target);
                }
                throw new InstallException('Could not remove the skin from the database; see the LibreNMS log.', 0, $e);
            }
            if ($gone !== null) {
                $this->removeTree($gone);
            }
        } finally {
            $this->unlock($lock);
        }
    }

    // ---- filesystem helpers ---------------------------------------------------------

    /**
     * @return resource
     */
    private function lock()
    {
        $this->ensureDir($this->publicDir);
        $handle = @fopen($this->publicDir . '/.install.lock', 'c');
        if ($handle === false || ! flock($handle, LOCK_EX)) {
            throw new InstallException('Could not take the install lock; check that the web server user can write ' . $this->publicDir . '.');
        }

        return $handle;
    }

    /**
     * @param  resource  $handle
     */
    private function unlock($handle): void
    {
        flock($handle, LOCK_UN);
        fclose($handle);
    }

    private function ensureDir(string $dir): void
    {
        if (! is_dir($dir) && ! @mkdir($dir, 0755, true) && ! is_dir($dir)) {
            throw new InstallException('Could not create ' . $dir . '; check that the web server user can write there.');
        }
    }

    /**
     * Remove staging and trash directories left by an interrupted install.
     */
    private function sweep(string $skinsDir): void
    {
        foreach (array_merge(glob($skinsDir . '/.stage-*') ?: [], glob($skinsDir . '/.old-*') ?: []) as $leftover) {
            if (@filemtime($leftover) < time() - 3600) {
                $this->removeTree($leftover);
            }
        }
    }

    /**
     * Delete a directory tree that must lie inside the skins directory. Links
     * are removed, never followed; anything that resolves elsewhere is refused.
     */
    private function removeTree(string $path): void
    {
        if (is_link($path)) {
            @unlink($path);

            return;
        }
        if (! is_dir($path)) {
            return;
        }
        $root = realpath($this->publicDir . '/skins');
        $real = realpath($path);
        if ($root === false || $real === false || ! str_starts_with($real, $root . DIRECTORY_SEPARATOR)) {
            return;
        }
        foreach (scandir($real) ?: [] as $entry) {
            if ($entry === '.' || $entry === '..') {
                continue;
            }
            $child = $real . '/' . $entry;
            if (is_dir($child) && ! is_link($child)) {
                $this->removeTree($child);
            } else {
                @unlink($child);
            }
        }
        @rmdir($real);
    }
}
